# Generated by Django 5.2.5 on 2025-09-09 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_posttag_post_alter_posttag_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='blog.tag'),
        ),
    ]
